version: '3.8'

services:
  frontend:
    image: frontend:latest
    container_name: front
    ports:
      - "80:80"
    networks:
      - app_net
    depends_on:
      - backend

  backend:
    image: backend:latest
    container_name: back
    ports:
      - "8080:8080"
    networks:
      - app_net

networks:
  app_net: